const ENVIRONMENT = process.env.PLASMO_PUBLIC_ENVIRONMENT
const SERVER_ORIGIN = process.env.PLASMO_PUBLIC_SERVER_ORIGIN

export { ENVIRONMENT, SERVER_ORIGIN }

// HTML INJECT ID's
const SIDEBAR_ELEMENT_INJECT_ID =
  "nav > div:nth-of-type(2) > div > div:nth-of-type(3)"
const PROMPT_INPUT_ELEMENT_INJECT_ID = "#prompt-textarea > p"
const PROMPT_LIST_ELEMENT_INJECT_ID =
  "main form > div"

export {
  SIDEBAR_ELEMENT_INJECT_ID,
  PROMPT_INPUT_ELEMENT_INJECT_ID,
  PROMPT_LIST_ELEMENT_INJECT_ID
}
